defaults:
  - _self_
  - app: base_my_app
  - override hydra/launcher: ray  # must be ray if we use distify.parallel_backend.ray

hydra:
  launcher:
    ray:
      init:
        address: 'auto'
        redis_password: '5241590000000000'

distify:
  # can be : 'ray', 'mp' (multiprocessing), 'mt' (multithreading), 'seq' (sequential, for debugging). 'ray' is recommended
  parallel_backend: 'ray'
  parallelize_checkpoint_retrieval: True
  checkpoint_frequency: 10
  requires_order: False
  timeout: null  #  timeout in seconds for each individual map application (doesn't work with time.sleep())
