defaults:
  - _self_
  - app: base_my_app
  - override hydra/launcher: ray

hydra:
  launcher:
    ray:
      init:
        address: 'auto'
        redis_password: '5241590000000000'

distify:
  parallel: True
  checkpoint_frequency: 10
