defaults:
  - _self_
  - app: base_my_app
  - override hydra/launcher: ray  # must be ray if we use distify.parallel_backend.ray

hydra:
  launcher:
    ray:
      init:
        address: 'auto'
        redis_password: '5241590000000000'

distify:
  # Always relevant
  # can be : 'ray', 'mp' (multiprocessing), 'mt' (multithreading), 'seq' (sequential, for debugging). 'ray' is recommended
  par_backend: 'seq'
  chunksize: 1

  # Only relevant if mp
  mp_context: 'spawn'

